#!/usr/bin/env python3
"""Expand nlp_* tokens with romanized / STT variants for Indic and other scripts."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOC = ROOT / "VisionCPRCoach" / "Resources" / "Localizations"

# Append romanized + common STT variants (pipe-separated merge).
EXPANSIONS: dict[str, dict[str, str]] = {
    "te": {
        "nlp_yes": "avunu|avun|aun|avvunu|ha|haa|sare|saredi|seri|correct|cheyanu|pilichanu|call chesanu|siddham|ready|yes|ok|okay",
        "nlp_no": "ledu|ledhu|kaadu|kaadhu|vadhu|kadu|no|nope|nah",
        "nlp_unsure": "teliyadu|telidhu|naku teliyadu|sure ga teliyadu|not sure|don't know|unsure",
        "nlp_emergency": "atyavaram|athyaavaram|sahayam|sahaayam|emergency|help|collapsed|unconscious|padipoyadu|heart attack",
        "nlp_responsive": "spandistunnadu|respond avutundi|kodutunnadu|conscious|moving|answered|woke",
        "nlp_unresponsive": "spandinchadam ledu|respond avvatledu|unconscious|unresponsive|padipoyadu",
        "nlp_breathing": "swasa|swasam|upiri|breathing|breath|respira",
        "nlp_not_breathing": "swasa ledu|upiri ledu|not breathing|no breathing|swasinchadam ledu",
        "nlp_gasping": "gasping|gasp|gasp chestunnadu|agonal",
        "nlp_called_ems": "pilichanu|call chesanu|chesanu|phone|112|911|ambulance|called|dial chesanu",
        "nlp_cant_call": "call cheyalekapotunna|phone ledu|ontariga|alone|no phone|can't call",
        "nlp_stop_cpr": "aapandi|apandi|stop cpr|melkonadu|breathing started|they woke",
        "nlp_question": "emiti|ela|enduku|eppudu|ekkada|what|how|why|when|where",
        "nlp_infant": "shishuvu|sisuvu|bidda|papa|baby|infant|newborn",
        "nlp_child": "pilla|pillalu|baludu|balika|child|kid|boy|girl",
        "nlp_adult": "pedda|manishi|vyaktulu|adult|man|woman|teen",
    },
    "hi": {
        "nlp_yes": "haan|han|ha|ji|ji haan|theek|thik|ho gaya|kar diya|call kar diya|tayyar|ready|yes|ok",
        "nlp_no": "nahin|nahi|na|no|nope|nah",
        "nlp_unsure": "pata nahi|pakka nahi|not sure|don't know|unsure",
        "nlp_emergency": "aapatkal|emergency|help|behosh|beshud|dil ka daura|collapsed",
        "nlp_responsive": "jawab diya|respond kar raha|hil raha|conscious|moving|answered",
        "nlp_unresponsive": "jawab nahi|respond nahi|behosh|unconscious|unresponsive",
        "nlp_breathing": "saans|sans|swas|breathing|breath",
        "nlp_not_breathing": "saans nahi|sans nahi|not breathing|no breathing",
        "nlp_gasping": "haanf raha|gasping|gasp",
        "nlp_called_ems": "call kar diya|phone kar diya|112|911|ambulance|called",
        "nlp_cant_call": "call nahi kar sakta|phone nahi|akela|alone|can't call",
        "nlp_stop_cpr": "rukun|stop cpr|jaag gaya|saans le raha",
        "nlp_question": "kya|kaise|kyun|kab|kahan|what|how|why",
        "nlp_infant": "shishu|baccha|baby|infant|newborn",
        "nlp_child": "baccha|bacha|ladka|ladki|child|kid",
        "nlp_adult": "bada|adult|aadmi|aurat|man|woman",
    },
    "ta": {
        "nlp_yes": "aam|am|sari|seri|ready|yes|ok|seithen|azhaithen|called",
        "nlp_no": "illai|illa|no|nope",
        "nlp_unsure": "theriyathu|theriyadu|not sure|don't know",
        "nlp_emergency": "avasaram|emergency|help|unconscious|collapsed",
        "nlp_responsive": "badhikirar|respond|conscious|moving",
        "nlp_unresponsive": "badhikala|unresponsive|unconscious",
        "nlp_breathing": "moochu|swasam|breathing|breath",
        "nlp_not_breathing": "moochu illa|not breathing",
        "nlp_gasping": "gasping|gasp",
        "nlp_called_ems": "azhaithen|call pannen|108|112|911|called",
        "nlp_cant_call": "call panna mudiyathu|phone illa|alone",
        "nlp_stop_cpr": "stop cpr|thangalama|thoongitar",
        "nlp_question": "enna|eppadi|why|what|how",
        "nlp_infant": "kuzhanthai|baby|infant",
        "nlp_child": "kuzhanthai|child|kid",
        "nlp_adult": "periya|adult|man|woman",
    },
    "bn": {
        "nlp_yes": "haan|han|ji|thik|ready|yes|ok|korechi|phone korechi",
        "nlp_no": "na|nai|no|nope",
        "nlp_unsure": "jani na|not sure|don't know",
        "nlp_emergency": "joruri|emergency|help|unconscious",
        "nlp_responsive": "sara dicche|conscious|moving",
        "nlp_unresponsive": "sara dicche na|unconscious|unresponsive",
        "nlp_breathing": "shash|breathing|breath",
        "nlp_not_breathing": "shash nei|not breathing",
        "nlp_gasping": "gasping|gasp",
        "nlp_called_ems": "phone korechi|999|112|911|called",
        "nlp_cant_call": "phone korte parchi na|alone",
        "nlp_stop_cpr": "stop cpr|jaglo|breathing",
        "nlp_question": "ki|kibhabe|keno|what|how",
        "nlp_infant": "shishu|baby|infant",
        "nlp_child": "baccha|child|kid",
        "nlp_adult": "adult|man|woman",
    },
    "mr": {
        "nlp_yes": "ho|hoy|bar|ready|yes|ok|kela|phone kela",
        "nlp_no": "nahi|naahi|no|nope",
        "nlp_unsure": "mahit nahi|not sure|don't know",
        "nlp_emergency": "aapatkal|emergency|help|unconscious",
        "nlp_responsive": "pratisad detoy|conscious|moving",
        "nlp_unresponsive": "pratisad nahi|unconscious|unresponsive",
        "nlp_breathing": "shwas|breathing|breath",
        "nlp_not_breathing": "shwas nahi|not breathing",
        "nlp_gasping": "gasping|gasp",
        "nlp_called_ems": "phone kela|108|112|911|called",
        "nlp_cant_call": "phone karu shakat nahi|alone",
        "nlp_stop_cpr": "stop cpr|jaga zala|breathing",
        "nlp_question": "kay|kase|ka|what|how",
        "nlp_infant": "arbak|bal|baby|infant",
        "nlp_child": "mul|child|kid",
        "nlp_adult": "adult|man|woman",
    },
    "ur": {
        "nlp_yes": "haan|han|ji|theek|ready|yes|ok|kar diya|phone kar diya",
        "nlp_no": "nahin|nahi|na|no|nope",
        "nlp_unsure": "nahi pata|not sure|don't know",
        "nlp_emergency": "emergency|madad|behosh|help",
        "nlp_responsive": "jawab de raha|conscious|moving",
        "nlp_unresponsive": "jawab nahi|behosh|unresponsive",
        "nlp_breathing": "saans|breathing|breath",
        "nlp_not_breathing": "saans nahi|not breathing",
        "nlp_gasping": "gasping|gasp",
        "nlp_called_ems": "phone kar diya|115|112|911|called",
        "nlp_cant_call": "phone nahi kar sakta|alone",
        "nlp_stop_cpr": "stop cpr|jag gaya|breathing",
        "nlp_question": "kya|kaise|kyun|what|how",
        "nlp_infant": "nawazaid|baby|infant",
        "nlp_child": "bachcha|child|kid",
        "nlp_adult": "adult|man|woman",
    },
    "pa": {
        "nlp_yes": "haan|han|ji|theek|ready|yes|ok|kar ditta|call kar ditta",
        "nlp_no": "nahin|nahi|na|no|nope",
        "nlp_unsure": "pata nahi|not sure|don't know",
        "nlp_emergency": "emergency|madad|behosh|help",
        "nlp_responsive": "jawab ditta|conscious|moving",
        "nlp_unresponsive": "jawab nahi|behosh|unresponsive",
        "nlp_breathing": "saans|breathing|breath",
        "nlp_not_breathing": "saans nahi|not breathing",
        "nlp_gasping": "gasping|gasp",
        "nlp_called_ems": "call kar ditta|112|911|called",
        "nlp_cant_call": "call nahi kar sakda|alone",
        "nlp_stop_cpr": "stop cpr|jag gaya|breathing",
        "nlp_question": "ki|kive|kyon|what|how",
        "nlp_infant": "baby|infant|bachcha",
        "nlp_child": "bachcha|child|kid",
        "nlp_adult": "adult|man|woman",
    },
    "ar": {
        "nlp_yes": "naam|na3am|aiwa|aywa|sah|tamam|ready|yes|ok|okay",
        "nlp_no": "la|laa|no|nope",
        "nlp_unsure": "ma adri|not sure|don't know",
        "nlp_emergency": "taware2|tawari|emergency|help|unconscious",
        "nlp_responsive": "yastajeeb|conscious|moving",
        "nlp_unresponsive": "la yastajeeb|unconscious|unresponsive",
        "nlp_breathing": "yata naffas|breathing|breath",
        "nlp_not_breathing": "la yata naffas|not breathing",
        "nlp_gasping": "gasping|gasp",
        "nlp_called_ems": "ittasalt|999|112|911|called",
        "nlp_cant_call": "ma aqdar atasil|alone",
        "nlp_stop_cpr": "stop cpr|sahaq|breathing",
        "nlp_question": "ma|kayf|limatha|what|how",
        "nlp_infant": "tifl|baby|infant",
        "nlp_child": "tifl|child|kid",
        "nlp_adult": "adult|man|woman",
    },
    "th": {
        "nlp_yes": "chai|krab|ka|ready|yes|ok|ok ka|ok krab",
        "nlp_no": "mai|mai chai|no|nope",
        "nlp_unsure": "mai roo|not sure|don't know",
        "nlp_emergency": "chuk chet|emergency|help|unconscious",
        "nlp_responsive": "tohn|conscious|moving",
        "nlp_unresponsive": "mai tohn|unconscious|unresponsive",
        "nlp_breathing": "hai chai|breathing|breath",
        "nlp_not_breathing": "mai hai chai|not breathing",
        "nlp_gasping": "gasping|gasp",
        "nlp_called_ems": "roh|1669|112|911|called",
        "nlp_cant_call": "roh mai dai|alone",
        "nlp_stop_cpr": "stop cpr|fun|breathing",
        "nlp_question": "arai|yang ngai|what|how",
        "nlp_infant": "tua lek|baby|infant",
        "nlp_child": "dek|child|kid",
        "nlp_adult": "adult|man|woman",
    },
    "ja": {
        "nlp_yes": "hai|ee|un|wakatta|ready|yes|ok|okay",
        "nlp_no": "iie|ie|no|nope",
        "nlp_unsure": "wakaranai|not sure|don't know",
        "nlp_emergency": "kinkyu|emergency|help|unconscious",
        "nlp_responsive": "kisho|conscious|moving",
        "nlp_unresponsive": "mushi|unconscious|unresponsive",
        "nlp_breathing": "kokyu|breathing|breath",
        "nlp_not_breathing": "kokyu nai|not breathing",
        "nlp_gasping": "gasping|gasp",
        "nlp_called_ems": "denwa|119|112|911|called",
        "nlp_cant_call": "denwa dekinai|alone",
        "nlp_stop_cpr": "stop cpr|mezameta|breathing",
        "nlp_question": "nani|dou|naze|what|how",
        "nlp_infant": "akachan|baby|infant",
        "nlp_child": "kodomo|child|kid",
        "nlp_adult": "otona|adult|man|woman",
    },
    "ko": {
        "nlp_yes": "ne|ye|yep|gwaenchanha|ready|yes|ok",
        "nlp_no": "ani|aniyo|no|nope",
        "nlp_unsure": "moreugesseoyo|not sure|don't know",
        "nlp_emergency": "ggeuda|emergency|help|unconscious",
        "nlp_responsive": "eungdab|conscious|moving",
        "nlp_unresponsive": "eungdab eopseo|unconscious|unresponsive",
        "nlp_breathing": "sum|breathing|breath",
        "nlp_not_breathing": "sum eopseo|not breathing",
        "nlp_gasping": "gasping|gasp",
        "nlp_called_ems": "jeonhwa|119|112|911|called",
        "nlp_cant_call": "jeonhwa mothae|alone",
        "nlp_stop_cpr": "stop cpr|kkaeeon|breathing",
        "nlp_question": "mwo|eotteoke|why|what|how",
        "nlp_infant": "agi|baby|infant",
        "nlp_child": "aedeul|child|kid",
        "nlp_adult": "seongin|adult|man|woman",
    },
    "zh-Hans": {
        "nlp_yes": "shi|dui|hao|keyi|ready|yes|ok",
        "nlp_no": "bu|bushi|mei|no|nope",
        "nlp_unsure": "bu zhidao|not sure|don't know",
        "nlp_emergency": "jinji|emergency|help|unconscious",
        "nlp_responsive": "you fanying|conscious|moving",
        "nlp_unresponsive": "mei fanying|unconscious|unresponsive",
        "nlp_breathing": "huxi|breathing|breath",
        "nlp_not_breathing": "mei huxi|not breathing",
        "nlp_gasping": "gasping|gasp",
        "nlp_called_ems": "120|112|911|called|da dianhua",
        "nlp_cant_call": "da bu liao dianhua|alone",
        "nlp_stop_cpr": "stop cpr|xing le|breathing",
        "nlp_question": "shenme|zenme|why|what|how",
        "nlp_infant": "yinger|baby|infant",
        "nlp_child": "haizi|child|kid",
        "nlp_adult": "chengren|adult|man|woman",
    },
    "fil": {
        "nlp_yes": "oo|opo|oo po|sige|yes|ok|okay|ready|tumawag na|called",
        "nlp_no": "hindi|hindi po|no|nope|wala",
        "nlp_unsure": "hindi ko alam|ewan|not sure|don't know",
        "nlp_emergency": "emergency|sakuna|tulong|unconscious|help",
        "nlp_responsive": "tumutugon|gumagalaw|conscious|moving",
        "nlp_unresponsive": "hindi tumutugon|unconscious|unresponsive",
        "nlp_breathing": "humihinga|breathing|breath",
        "nlp_not_breathing": "hindi humihinga|not breathing",
        "nlp_gasping": "gasping|gasp|umuungol",
        "nlp_called_ems": "tumawag na|called|911|117|112|ambulansya",
        "nlp_cant_call": "hindi makatawag|walang phone|alone",
        "nlp_stop_cpr": "itigil ang cpr|gumising|humihinga na|stop cpr",
        "nlp_question": "ano|bakit|paano|what|how|why",
        "nlp_infant": "sanggol|baby|infant|bebe",
        "nlp_child": "bata|child|kid|anak",
        "nlp_adult": "matanda|adult|lalaki|babae",
    },
    "vi": {
        "nlp_yes": "co|vang|duoc|yes|ok|ready|da goi|called",
        "nlp_no": "khong|ko|no|nope",
        "nlp_unsure": "khong biet|not sure|don't know",
        "nlp_emergency": "khan cap|emergency|help|unconscious",
        "nlp_responsive": "phan ung|conscious|moving",
        "nlp_unresponsive": "khong phan ung|unconscious|unresponsive",
        "nlp_breathing": "tho|breathing|breath",
        "nlp_not_breathing": "khong tho|not breathing",
        "nlp_gasping": "gasping|gasp",
        "nlp_called_ems": "da goi|115|112|911|called",
        "nlp_cant_call": "khong goi duoc|alone|no phone",
        "nlp_stop_cpr": "stop cpr|tinh lai|breathing",
        "nlp_question": "gi|sao|the nao|what|how",
        "nlp_infant": "em be|baby|infant",
        "nlp_child": "tre|child|kid",
        "nlp_adult": "nguoi lon|adult|man|woman",
    },
    "id": {
        "nlp_yes": "iya|ya|ok|yes|ready|sudah|sudah telepon|called",
        "nlp_no": "tidak|ngga|no|nope",
        "nlp_unsure": "tidak tahu|not sure|don't know",
        "nlp_emergency": "darurat|emergency|help|unconscious",
        "nlp_responsive": "merespon|conscious|moving",
        "nlp_unresponsive": "tidak merespon|unconscious|unresponsive",
        "nlp_breathing": "napas|breathing|breath",
        "nlp_not_breathing": "tidak napas|not breathing",
        "nlp_gasping": "gasping|gasp",
        "nlp_called_ems": "sudah telepon|112|911|called|ambulans",
        "nlp_cant_call": "tidak bisa telepon|alone|no phone",
        "nlp_stop_cpr": "stop cpr|bangun|breathing",
        "nlp_question": "apa|bagaimana|mengapa|what|how",
        "nlp_infant": "bayi|baby|infant",
        "nlp_child": "anak|child|kid",
        "nlp_adult": "dewasa|adult|man|woman",
    },
    "ru": {
        "nlp_yes": "da|da da|ok|yes|ready|pozvonil|called",
        "nlp_no": "net|ne|no|nope",
        "nlp_unsure": "ne znayu|not sure|don't know",
        "nlp_emergency": "srochno|emergency|help|bez soznaniya|unconscious",
        "nlp_responsive": "otvechaet|conscious|moving",
        "nlp_unresponsive": "ne otvechaet|unconscious|unresponsive",
        "nlp_breathing": "dyshit|breathing|breath",
        "nlp_not_breathing": "ne dyshit|not breathing",
        "nlp_gasping": "gasping|gasp",
        "nlp_called_ems": "pozvonil|112|911|called|skoraya",
        "nlp_cant_call": "ne mogu pozvonit|alone|no phone",
        "nlp_stop_cpr": "stop cpr|prosnulsya|breathing",
        "nlp_question": "chto|kak|pochemu|what|how",
        "nlp_infant": "mladenets|baby|infant",
        "nlp_child": "rebenok|child|kid",
        "nlp_adult": "vzrosly|adult|man|woman",
    },
    "zh-Hant": {
        "nlp_yes": "shi|dui|hao|keyi|ready|yes|ok",
        "nlp_no": "bu|bushi|mei|no|nope",
        "nlp_unsure": "bu zhidao|not sure|don't know",
        "nlp_emergency": "jinji|emergency|help|unconscious",
        "nlp_responsive": "you fanying|conscious|moving",
        "nlp_unresponsive": "mei fanying|unconscious|unresponsive",
        "nlp_breathing": "huxi|breathing|breath",
        "nlp_not_breathing": "mei huxi|not breathing",
        "nlp_gasping": "gasping|gasp",
        "nlp_called_ems": "119|112|911|called|da dianhua",
        "nlp_cant_call": "da bu liao dianhua|alone",
        "nlp_stop_cpr": "stop cpr|xing le|breathing",
        "nlp_question": "shenme|zenme|why|what|how",
        "nlp_infant": "yinger|baby|infant",
        "nlp_child": "haizi|child|kid",
        "nlp_adult": "chengren|adult|man|woman",
    },
}


def merge_tokens(existing: str, extra: str) -> str:
    parts: list[str] = []
    seen: set[str] = set()
    for chunk in (existing + "|" + extra).split("|"):
        t = chunk.strip()
        key = t.casefold()
        if t and key not in seen:
            seen.add(key)
            parts.append(t)
    return "|".join(parts)


def main() -> None:
    for code, extras in EXPANSIONS.items():
        path = LOC / f"{code}.json"
        data = json.load(open(path, encoding="utf-8"))
        for key, extra in extras.items():
            data[key] = merge_tokens(data.get(key, ""), extra)
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print("expanded", code)


if __name__ == "__main__":
    main()
